### ISSUE TITLE
Registered function IDs must be prefixed with client ID

### ISSUE THREAD

**Issue by jpwilliams** [inngest/inngestgo#24]
When registering functions, their ID isn't prefixed with the client's ID, potentially resulting in deploys fighting for the same namespace.

```go
// Reports `"my-example-fn"` instead of `"client-id-my-example-fn"`.
inngestgo.CreateFunction(
		inngestgo.FunctionOpts{
			Name: "My Example Fn",
		},
```

**Comment by perebaj** [comment]
Hello, I'm taking a look at this code and trying to wonder what the best way to solve this bug! 

What you are trying to propose is to generate the ID using some different rule instead of just creating a slug on top of the Name?
