### ISSUE TITLE
go.mod dependency on an unreleased commit hash (bf40aa29d3af)

### ISSUE THREAD

**Issue by api-moose** [inngest/inngestgo#40]
### I ran the following commands

$ go clean -modcache
$ go get github.com/inngest/inngestgo

### The following error was returned

go: downloading github.com/inngest/inngestgo v0.6.2
go: downloading github.com/gosimple/slug v1.12.0
go: downloading github.com/inngest/inngest v0.26.3-0.20240229121853-bf40aa29d3af
go: downloading golang.org/x/exp v0.0.0-20230626212559-97b1e661b5df
go: downloading github.com/gosimple/unidecode v1.0.1
go: downloading github.com/xhit/go-str2duration/v2 v2.1.0
go: github.com/inngest/inngestgo imports
        github.com/inngest/inngest/pkg/enums: github.com/inngest/inngest@v0.26.3-0.20240229121853-bf40aa29d3af: invalid version: unknown revision bf40aa29d3af
go: github.com/inngest/inngestgo imports
        github.com/inngest/inngest/pkg/execution/state: github.com/inngest/inngest@v0.26.3-0.20240229121853-bf40aa29d3af: invalid version: unknown revision bf40aa29d3af
go: github.com/inngest/inngestgo imports
        github.com/inngest/inngest/pkg/inngest: github.com/inngest/inngest@v0.26.3-0.20240229121853-bf40aa29d3af: invalid version: unknown revision bf40aa29d3af
go: github.com/inngest/inngestgo imports
        github.com/inngest/inngest/pkg/publicerr: github.com/inngest/inngest@v0.26.3-0.20240229121853-bf40aa29d3af: invalid version: unknown revision bf40aa29d3af
go: github.com/inngest/inngestgo imports
        github.com/inngest/inngest/pkg/sdk: github.com/inngest/inngest@v0.26.3-0.20240229121853-bf40aa29d3af: invalid version: unknown revision bf40aa29d3af
go: downloading golang.org/x/sync v0.6.0

It seems like this may be an issue with the go.mod file in the inngestgo repository.

**Comment by tonyhb** [comment]
@api-moose fixed, thank you!
